<a href="https://colab.research.google.com/github/nt5504289-oss/GEN-AI/blob/main/project_of_student_marks_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks_array = np.array([[23,54,67],
                  [87,98,87],
                  [98,88,78],
                  [56,87,45],
                  [56,89,65]])
print(marks_array)


[[23 54 67]
 [87 98 87]
 [98 88 78]
 [56 87 45]
 [56 89 65]]


In [ ]:
print(marks_array.shape)

(5, 3)


In [ ]:
print(marks_array.ndim)

2


In [ ]:
print("Average Marks:", np.mean(marks_array))
print("Max Marks:" , np.max(marks_array))
print("Min Marks:" , np.min(marks_array))
print("Sum of Marks:" , np.sum(marks_array))

Average Marks: 71.86666666666666
Max Marks: 98
Min Marks: 23
Sum of Marks: 1078


In [ ]:
#column wise subject--axis=0 and row wise subject--axis=1

In [ ]:
subject_avg = np.mean(marks_array, axis=0)
subject_max = np.max(marks_array, axis=0)
subject_min = np.min(marks_array, axis=1)
print(subject_avg)
print(subject_max)
print(subject_min)


[64.  83.2 68.4]
[98 98 87]
[23 87 78 45 56]


In [ ]:
#count pass and fail student in column and row wise

In [ ]:
student_pass = np.sum(marks_array >=50, axis=1)
student_fail = np.sum(marks_array <=30, axis=1)

print(student_pass)
print(student_fail)

[2 3 3 2 3]
[1 0 0 0 0]


In [ ]:
student_pass = np.sum(marks_array >=50, axis=0)
student_fail = np.sum(marks_array <=30, axis=0)

print(student_pass)
print(student_fail)


[4 5 4]
[1 0 0]


In [ ]:
# find toppers

In [ ]:
topper_student = np.sum(marks_array >=90, axis=1)
print(topper_student)

[0 1 1 0 0]


In [ ]:
toppr_index = np.argmax(topper_student)
print(topper_index)

4


In [ ]:
# student grades

In [ ]:
grade = np.where(marks_array>=90, 'A',
    np.where(marks_array>=80,'B',
        np.where(marks_array>=50,'C',
            np.where(marks_array>=30,'D',
                np.where(marks_array>=20, 'E','F')
            ))
        ))


print(grade)

[['E' 'C' 'C']
 ['B' 'A' 'B']
 ['A' 'B' 'C']
 ['C' 'B' 'D']
 ['C' 'B' 'C']]


In [ ]:
for avg in student_avg:
  if avg >= 90:
    grade.append('A')
    elif avg >= 80:
      grade.append('B')
      elif avg >= 50:
        grade.append('C')
        elif avg >=30:
          grade.append('D')
          elif avg >=20:
            grade.append('E')
            else:
            grade.append('F')


In [ ]:
print("Grade",grade)

Grade [['E' 'C' 'C']
 ['B' 'A' 'B']
 ['A' 'B' 'C']
 ['C' 'B' 'D']
 ['C' 'B' 'C']]


In [ ]:
# GIVE RANK TO STUDENT

In [ ]:
total_marks = np.sum(marks_array, axis=1)
print(total_marks)

[144 272 264 188 210]


In [ ]:
sorted_indices = np.argsort(total_marks)
print(sorted_indices)

[0 3 4 2 1]
